import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use — Invoera",
};

const h2 = "mt-8 text-lg font-bold text-gray-900 dark:text-gray-100";
const p = "mt-3 text-sm leading-relaxed text-gray-600 dark:text-gray-300";
const ul = "mt-3 flex flex-col gap-2 text-sm leading-relaxed text-gray-600 dark:text-gray-300";
const li = "flex gap-2 before:mt-2 before:h-1 before:w-1 before:shrink-0 before:rounded-full before:bg-teal-500";

export default function TermsOfUsePage() {
  return (
    <article>
      <p className="text-xs font-semibold uppercase tracking-wide text-teal-600 dark:text-teal-400">
        Legal
      </p>
      <h1 className="mt-2 text-2xl font-bold text-gray-900 dark:text-gray-100">Terms of Use</h1>
      <p className="mt-1 text-sm text-gray-400 dark:text-gray-500">Last updated: July 6, 2026</p>

      <p className={p}>
        These terms govern your use of Invoera. By creating an account, you agree to them. If
        you don&apos;t agree, please don&apos;t use the app.
      </p>

      <h2 className={h2}>1. The service</h2>
      <p className={p}>
        Invoera lets you upload invoices and receipts, which an AI pipeline extracts, validates,
        and categorizes for you, and gives you a dashboard summarizing your invoicing and
        spending activity, including conversion between currencies for display purposes.
      </p>

      <h2 className={h2}>2. Your account</h2>
      <ul className={ul}>
        <li className={li}>You must be at least 16 years old to use Invoera.</li>
        <li className={li}>You&apos;re responsible for keeping your login credentials secure.</li>
        <li className={li}>
          Information you provide (email, display name, invoice and expense data) must be accurate
          to the best of your knowledge.
        </li>
        <li className={li}>One account per person; don&apos;t share credentials.</li>
      </ul>

      <h2 className={h2}>3. Acceptable use</h2>
      <p className={p}>You agree not to:</p>
      <ul className={ul}>
        <li className={li}>Upload documents you don&apos;t have the right to use, or content that is illegal, fraudulent, or infringes someone else&apos;s rights.</li>
        <li className={li}>Attempt to bypass rate limits, security controls, or access another user&apos;s data.</li>
        <li className={li}>Use the service to send spam or abuse the notification/email system.</li>
        <li className={li}>Reverse-engineer, scrape, or resell the service without permission.</li>
      </ul>
      <p className={p}>
        We may suspend or terminate accounts that violate these terms, including accounts that
        repeatedly trigger abuse or security protections.
      </p>

      <h2 className={h2}>4. AI-extracted data is a starting point, not a guarantee</h2>
      <p className={p}>
        Amounts, dates, categories, and currencies extracted from your uploads are generated by an
        AI model and may contain mistakes. Invoera always shows you an extracted result for
        review before saving it — you&apos;re responsible for checking it&apos;s correct before
        relying on it for accounting, tax, or any other purpose.
      </p>

      <h2 className={h2}>5. Currency conversion</h2>
      <p className={p}>
        Converted amounts shown on your dashboard use daily reference exchange rates from a
        third-party source and are provided for informational display only — they are not
        suitable for settlement, trading, or official accounting conversions.
      </p>

      <h2 className={h2}>6. Your data</h2>
      <p className={p}>
        You retain ownership of the invoices, expenses, and documents you upload. You&apos;re
        granting us only the access needed to store it and run it through the AI pipeline you
        requested. See our{" "}
        <Link href="/privacy" className="text-teal-600 hover:underline dark:text-teal-400">
          Privacy Policy
        </Link>{" "}
        for details.
      </p>

      <h2 className={h2}>7. No warranty</h2>
      <p className={p}>
        Invoera is provided "as is," without warranties of any kind. We don&apos;t guarantee the
        service will be uninterrupted, error-free, or that AI extraction will always be accurate.
      </p>

      <h2 className={h2}>8. Limitation of liability</h2>
      <p className={p}>
        To the fullest extent permitted by law, Invoera is not liable for indirect, incidental,
        or consequential damages, including financial decisions made based on AI-extracted data or
        converted currency amounts.
      </p>

      <h2 className={h2}>9. Changes to these terms</h2>
      <p className={p}>
        We may update these terms from time to time. If we make material changes, we&apos;ll
        update the date above. Continuing to use Invoera after a change means you accept the
        updated terms.
      </p>

      <h2 className={h2}>10. Contact</h2>
      <p className={p}>
        Questions about these terms? Email{" "}
        <a href="mailto:support@invoera.app" className="text-teal-600 hover:underline dark:text-teal-400">
          support@invoera.app
        </a>
        .
      </p>
    </article>
  );
}
